# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [ ]:
# Modifying the DataFrame and including some dirty data for cleaning practice

import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""],
    "Email": ["alice@email.com", None, "", "david@email.com", "wrong_email"]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score            Email
0    Alice      25     2022-01-01  95.5  alice@email.com
1      Bob  thirty     not a date  None              NaN
2  Charlie      35     2022/03/01  88.0
3    David     NaN            NaN  92.5  david@email.com
4      NaN      40  April 5, 2022            wrong_email

In [18]:
# Checking for missing values in the DataFrame
print("Missing values per column:")
print(df.isnull().sum())

print("\nEmpty strings per column:")
print((df == "").sum())

Missing values per column:
Name           1
Age            1
Signup Date    1
Score          1
Email          1
dtype: int64

Empty strings per column:
Name           0
Age            0
Signup Date    0
Score          1
Email          1
dtype: int64

In [20]:
# Convertng the "Age" column to numeric, coercing errors to NaN
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df

      Name   Age    Signup Date Score            Email
0    Alice  25.0     2022-01-01  95.5  alice@email.com
1      Bob   NaN     not a date  None              NaN
2  Charlie  35.0     2022/03/01  88.0
3    David   NaN            NaN  92.5  david@email.com
4      NaN  40.0  April 5, 2022            wrong_email

In [ ]:
# Convert signup date to datetime, coercing errors to NaT
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df

      Name   Age Signup Date Score            Email
0    Alice  25.0  2022-01-01  95.5  alice@email.com
1      Bob   NaN         NaT  None              NaN
2  Charlie  35.0         NaT  88.0
3    David   NaN         NaT  92.5  david@email.com
4      NaN  40.0         NaT            wrong_email

In [22]:
# Convert Score 
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df

      Name   Age Signup Date  Score            Email
0    Alice  25.0  2022-01-01   95.5  alice@email.com
1      Bob   NaN         NaT    NaN              NaN
2  Charlie  35.0         NaT   88.0
3    David   NaN         NaT   92.5  david@email.com
4      NaN  40.0         NaT    NaN      wrong_email

In [23]:
# Replace empty strings in the "Email" column with NaN
df["Email"] = df["Email"].replace("", np.nan)
df

      Name   Age Signup Date  Score            Email
0    Alice  25.0  2022-01-01   95.5  alice@email.com
1      Bob   NaN         NaT    NaN              NaN
2  Charlie  35.0         NaT   88.0              NaN
3    David   NaN         NaT   92.5  david@email.com
4      NaN  40.0         NaT    NaN      wrong_email

In [24]:
# Fill missing values
print("Final missing values:")
print(df.isnull().sum())

df.info()
print(df.describe(include="all"))

Final missing values:
Name           1
Age            2
Signup Date    4
Score          2
Email          2
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      str
 1   Age          3 non-null      float64
 2   Signup Date  1 non-null      datetime64[us]
 3   Score        3 non-null      float64
 4   Email        3 non-null      str
dtypes: datetime64[us](1), float64(2), str(2)
memory usage: 332.0 bytes
         Name        Age          Signup Date      Score            Email
count       4   3.000000                    1   3.000000                3
unique      4        NaN                  NaN        NaN                3
top     Alice        NaN                  NaN        NaN  alice@email.com
freq        1        NaN                  NaN        NaN                1
mean      NaN  33.333333  2022-01-01 00:00:00  92.000000              NaN
min       NaN  25.000000  2022-01-01 00:00:00  88.000000              NaN
25%       NaN  30.000000  2022-01-01 00:00:00  90.250000              NaN
50%       NaN  35.000000  2022-01-01 00:00:00  92.500000              NaN
75%       NaN  37.500000  2022-01-01 00:00:00  94.000000              NaN
max       NaN  40.000000  2022-01-01 00:00:00  95.500000              NaN
std       NaN   7.637626                  NaN   3.774917              NaN

### 🧯 2. Detecting Missing or Broken Values

In [2]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [3]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN            NaN  92.5
4    NaN      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [5]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [6]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [7]:
df.dtypes

Name              str
Age            object
Signup Date       str
Score          object
dtype: object

In [8]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                      str
Age                   float64
Signup Date    datetime64[us]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [9]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/var/folders/v4/p638bcqn6zs4xjj6821ngpv40000gn/T/ipykernel_66280/1713118361.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].median(), inplace=True)
/var/folders/v4/p638bcqn6zs4xjj6821ngpv40000gn/T/ipykernel_66280/1713118361.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Score"].fillna(df["Score"].mean(), inplace=True)

0    95.5
1    92.0
2    88.0
3    92.5
4    92.0
Name: Score, dtype: float64

In [10]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/var/folders/v4/p638bcqn6zs4xjj6821ngpv40000gn/T/ipykernel_66280/3000949103.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

0   2022-01-01
1   2022-01-01
2   2022-01-01
3   2022-01-01
4   2022-01-01
Name: Signup Date, dtype: datetime64[us]

In [11]:
df["Name"].fillna("Unknown", inplace=True)

/var/folders/v4/p638bcqn6zs4xjj6821ngpv40000gn/T/ipykernel_66280/626038248.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Name"].fillna("Unknown", inplace=True)

0      Alice
1        Bob
2    Charlie
3      David
4    Unknown
Name: Name, dtype: str

### 🤓 6. Cleaned Data Review

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      str
 1   Age          3 non-null      float64
 2   Signup Date  1 non-null      datetime64[us]
 3   Score        3 non-null      float64
dtypes: datetime64[us](1), float64(2), str(1)
memory usage: 292.0 bytes

In [13]:
df.describe(include="all")

         Name        Age          Signup Date      Score
count       4   3.000000                    1   3.000000
unique      4        NaN                  NaN        NaN
top     Alice        NaN                  NaN        NaN
freq        1        NaN                  NaN        NaN
mean      NaN  33.333333  2022-01-01 00:00:00  92.000000
min       NaN  25.000000  2022-01-01 00:00:00  88.000000
25%       NaN  30.000000  2022-01-01 00:00:00  90.250000
50%       NaN  35.000000  2022-01-01 00:00:00  92.500000
75%       NaN  37.500000  2022-01-01 00:00:00  94.000000
max       NaN  40.000000  2022-01-01 00:00:00  95.500000
std       NaN   7.637626                  NaN   3.774917

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

### 🧠 Mini-Challenge

> 🗂 Load `"../../data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [28]:
import pandas as pd
import numpy as np

survey = pd.read_csv("../../data/survey.csv")
survey.head()

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

In [29]:
# Print missing values per column
print("Missing values per column: ")
print(survey.isnull().sum())

Missing values per column:
student_id               0
age                     33
gender                  23
major                   10
gpa                     44
study_hours_per_week    42
satisfaction_1_5        46
survey_date             32
dorm_resident           33
expected_grad_year      33
income_range            21
commute_minutes         53
clubs_member            25
attendance_rate         79
favorite_language       19
comments                52
dtype: int64

In [30]:
# Print summary
print("\nDataFrame info: ")
survey.info()
print(survey.describe(include="all"))

DataFrame info:
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            120 non-null    str
 1   age                   87 non-null     str
 2   gender                97 non-null     str
 3   major                 110 non-null    str
 4   gpa                   76 non-null     str
 5   study_hours_per_week  78 non-null     str
 6   satisfaction_1_5      74 non-null     str
 7   survey_date           88 non-null     str
 8   dorm_resident         87 non-null     str
 9   expected_grad_year    87 non-null     str
 10  income_range          99 non-null     str
 11  commute_minutes       67 non-null     str
 12  clubs_member          95 non-null     str
 13  attendance_rate       41 non-null     str
 14  favorite_language     101 non-null    str
 15  comments              68 non-null     str
dtypes: str(16)
memory usage: 15.1 KB
       student_id age gender major   gpa study_hours_per_week  \
count         120  87     97   110    76                   78
unique        120   9      4     9    14                   14
top        S10000  19   Male    CS  3.75                   -3
freq            1  16     28    20    22                   15

       satisfaction_1_5 survey_date dorm_resident expected_grad_year  \
count                74          88            87                 87
unique                6          60             4                  6
top                   2  2025-13-40           Yes               2027
freq                 18          27            29                 19

       income_range commute_minutes clubs_member attendance_rate  \
count            99              67           95              41
unique            6              16            6              14
top          >$100k              -5            1            105%
freq             22              17           25              25

       favorite_language          comments
count                101                68
unique                 7                 4
top                 Rust  Love the course.
freq                  18                22

In [31]:
# Treating empty string like missig values
survey = survey.replace(["", "NA", "N/A", "null", "NULL", "NONE", "none", "Missing", "MISSING"], np.nan)
print(survey.isnull().sum())

student_id               0
age                     33
gender                  23
major                   10
gpa                     44
study_hours_per_week    42
satisfaction_1_5        46
survey_date             32
dorm_resident           33
expected_grad_year      33
income_range            21
commute_minutes         53
clubs_member            25
attendance_rate         79
favorite_language       19
comments                52
dtype: int64

In [32]:
# Inspecting columns
print(survey.columns.tolist())

['student_id', 'age', 'gender', 'major', 'gpa', 'study_hours_per_week', 'satisfaction_1_5', 'survey_date', 'dorm_resident', 'expected_grad_year', 'income_range', 'commute_minutes', 'clubs_member', 'attendance_rate', 'favorite_language', 'comments']

In [33]:
# Cleaning Up
for col in survey.columns:
    if "age" in col.lower() or "score" in col.lower() or "income" in col.lower():
        survey[col] = pd.to_numeric(survey[col], errors="coerce")
    if "date" in col.lower():
        survey[col] = pd.to_datetime(survey[col], errors="coerce")

/var/folders/v4/p638bcqn6zs4xjj6821ngpv40000gn/T/ipykernel_66280/3656056969.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  survey[col] = pd.to_datetime(survey[col], errors="coerce")

In [34]:
# Fill in missing values
for col in survey.select_dtypes(include=["number"]).columns:
    survey[col] = survey[col].fillna(survey[col].median())

for col in survey.select_dtypes(include=["object"]).columns:
    survey[col] = survey[col].fillna("Unknown")

/var/folders/v4/p638bcqn6zs4xjj6821ngpv40000gn/T/ipykernel_66280/233097329.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in survey.select_dtypes(include=["object"]).columns:

In [35]:
# Final Clean Report
print("Final missing values: ")
print(survey.isnull().sum())

survey.info()
print(survey.describe(include="all"))
survey.head()

Final missing values:
student_id                0
age                       0
gender                    0
major                     0
gpa                       0
study_hours_per_week      0
satisfaction_1_5          0
survey_date              59
dorm_resident             0
expected_grad_year        0
income_range            120
commute_minutes           0
clubs_member              0
attendance_rate           0
favorite_language       120
comments                  0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            120 non-null    str
 1   age                   120 non-null    float64
 2   gender                120 non-null    str
 3   major                 120 non-null    str
 4   gpa                   120 non-null    str
 5   study_hours_per_week  120 non-null    str
 6   satisfaction_1_5      120 non-null    str
 7   survey_date           61 non-null     datetime64[us]
 8   dorm_resident         120 non-null    str
 9   expected_grad_year    120 non-null    str
 10  income_range          0 non-null      float64
 11  commute_minutes       120 non-null    str
 12  clubs_member          120 non-null    str
 13  attendance_rate       120 non-null    str
 14  favorite_language     0 non-null      float64
 15  comments              120 non-null    str
dtypes: datetime64[us](1), float64(3), str(12)
memory usage: 15.1 KB
       student_id         age gender major      gpa study_hours_per_week  \
count         120  120.000000    120   120      120                  120
unique        120         NaN      5    10       15                   15
top        S10000         NaN   Male    CS  Unknown              Unknown
freq            1         NaN     28    20       44                   42
mean          NaN   21.158333    NaN   NaN      NaN                  NaN
min           NaN   18.000000    NaN   NaN      NaN                  NaN
25%           NaN   20.000000    NaN   NaN      NaN                  NaN
50%           NaN   21.000000    NaN   NaN      NaN                  NaN
75%           NaN   22.000000    NaN   NaN      NaN                  NaN
max           NaN   25.000000    NaN   NaN      NaN                  NaN
std           NaN    1.887579    NaN   NaN      NaN                  NaN

       satisfaction_1_5                 survey_date dorm_resident  \
count               120                          61           120
unique                7                         NaN             5
top             Unknown                         NaN       Unknown
freq                 46                         NaN            33
mean                NaN  2025-10-20 21:14:45.245901           NaN
min                 NaN         2025-09-02 00:00:00           NaN
25%                 NaN         2025-10-02 00:00:00           NaN
50%                 NaN         2025-10-28 00:00:00           NaN
75%                 NaN         2025-11-08 00:00:00           NaN
max                 NaN         2025-11-30 00:00:00           NaN
std                 NaN                         NaN           NaN

       expected_grad_year  income_range commute_minutes clubs_member  \
count                 120           0.0             120          120
unique                  7           NaN              17            7
top               Unknown           NaN         Unknown            1
freq                   33           NaN              53           25
mean                  NaN           NaN             NaN          NaN
min                   NaN           NaN             NaN          NaN
25%                   NaN           NaN             NaN          NaN
50%                   NaN           NaN             NaN          NaN
75%                   NaN           NaN             NaN          NaN
max                   NaN           NaN             NaN          NaN
std                   NaN           NaN             NaN          NaN

       attendance_rate  favorite_language comments
count              120                0.0      120
unique              15                NaN        5
top            Unknown                NaN  Unknown
freq                79                NaN       52
mean               NaN                NaN      NaN
min                NaN                NaN      NaN
25%                NaN                NaN      NaN
50%                NaN                NaN      NaN
75%                NaN                NaN      NaN
max                NaN                NaN      NaN
std                NaN                NaN      NaN

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,21.0,Male,Computer Science,Unknown,Unknown,2,NaT,Yes,2027,NaN,54,TRUE,105%,NaN,Love the course.
1,S10001,21.0,Male,CompSci,3.75,-3,Unknown,NaT,Yes,Unknown,NaN,Unknown,1,Unknown,NaN,Lectures are 🔥
2,S10002,23.0,Male,Data Science,Unknown,20,5,NaT,Unknown,2027,NaN,Unknown,Unknown,64%,NaN,Unknown
3,S10003,21.0,Female,History,5.1,Unknown,Unknown,NaT,No,Unknown,NaN,15,No,105%,NaN,Unknown
4,S10004,21.0,Female,CompSci,Unknown,0,5,NaT,Yes,2029,NaN,41,No,Unknown,NaN,Unknown

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |