# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [38]:
import pandas as pd

df = pd.read_csv("../../data/students.csv")
df.head()

,first_name,last_name,math_score,science_score,signup_date,survey_completed,major,grade_level
0,Danielle,Wood,100,95,2025-03-28,Yes,CS,Senior
1,Angel,Clark,67,78,2025-03-14,Yes,Math,Sophomore
2,Joshua,Adams,61,100,2025-03-31,Yes,Biology,Freshman
3,Jeffrey,Zuniga,77,99,2025-03-25,Yes,History,Junior
4,Jill,Wong,75,83,2025-03-09,Yes,CS,Senior

### 🔢 2. Sorting Data

In [2]:
# Sort by math_score
df.sort_values(by="math_score")

     first_name  last_name  math_score  science_score
28      Melanie      Baker          60             94
2        Joshua      Adams          61            100
13        James      Cohen          61             66
19         Adam      Adams          61             70
44  Christopher      Brown          62             64
12      Anthony    Hawkins          62             74
49      Michael   Valencia          65             91
14        Debra    Cameron          65             84
37    Christine      Hicks          65             80
9       Anthony       Gray          65             74
36        Maria     Bright          66             74
39      Barbara   Williams          66             74
7   Christopher     Daniel          66             64
47       Joshua       Rice          67             80
1         Angel      Clark          67             78
6      Patricia    Jackson          68             72
33       Teresa      Hurst          69             77
29    Cassandra     Wright          70             75
21        Helen       Hahn          72             82
34     Nicholas       Ross          73            100
15          Amy    Parsons          73             77
24        Susan       Rios          74             64
5         Erica      Lynch          74             96
16      Jeffrey      Perez          74             89
4          Jill       Wong          75             83
43        Keith  Henderson          76             77
3       Jeffrey     Zuniga          77             99
27        Colin      Ellis          77             70
32       Amanda   Richards          77             84
35       Andrea   Robinson          81             95
31      Jessica      Baker          81             89
40        Janet  Rodriguez          82             62
41      Brandon     Burton          82             80
48      Cynthia     Maddox          84             73
38     Michelle      Davis          84             63
23         Eric    Edwards          86             77
11      William     Bowman          87             65
30      Lindsay    Hoffman          87             70
25      Matthew     Foster          88             98
45        Jesse      James          89             73
17      Bridget    Johnson          92            100
46        Craig    Ferrell          94             96
22      Matthew     Walter          94             73
8        Robert     Martin          94             62
20        Linda      Clark          95             83
10      Jeffery       Mayo          97             78
26  Christopher      Rocha          97            100
18         Lisa    Stewart          98             83
42       Jeremy     Conner          98             85
0      Danielle       Wood         100             95

In [3]:
# Sort by science_score descending
df.sort_values(by="science_score", ascending=False)

     first_name  last_name  math_score  science_score
17      Bridget    Johnson          92            100
2        Joshua      Adams          61            100
34     Nicholas       Ross          73            100
26  Christopher      Rocha          97            100
3       Jeffrey     Zuniga          77             99
25      Matthew     Foster          88             98
46        Craig    Ferrell          94             96
5         Erica      Lynch          74             96
35       Andrea   Robinson          81             95
0      Danielle       Wood         100             95
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
16      Jeffrey      Perez          74             89
31      Jessica      Baker          81             89
42       Jeremy     Conner          98             85
14        Debra    Cameron          65             84
32       Amanda   Richards          77             84
4          Jill       Wong          75             83
18         Lisa    Stewart          98             83
20        Linda      Clark          95             83
21        Helen       Hahn          72             82
47       Joshua       Rice          67             80
41      Brandon     Burton          82             80
37    Christine      Hicks          65             80
1         Angel      Clark          67             78
10      Jeffery       Mayo          97             78
43        Keith  Henderson          76             77
23         Eric    Edwards          86             77
33       Teresa      Hurst          69             77
15          Amy    Parsons          73             77
29    Cassandra     Wright          70             75
36        Maria     Bright          66             74
39      Barbara   Williams          66             74
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
45        Jesse      James          89             73
22      Matthew     Walter          94             73
48      Cynthia     Maddox          84             73
6      Patricia    Jackson          68             72
30      Lindsay    Hoffman          87             70
27        Colin      Ellis          77             70
19         Adam      Adams          61             70
13        James      Cohen          61             66
11      William     Bowman          87             65
7   Christopher     Daniel          66             64
44  Christopher      Brown          62             64
24        Susan       Rios          74             64
38     Michelle      Davis          84             63
40        Janet  Rodriguez          82             62
8        Robert     Martin          94             62

In [4]:
# Sort by multiple columns
df.sort_values(by=["science_score", "math_score"], ascending=[False, True])

     first_name  last_name  math_score  science_score
2        Joshua      Adams          61            100
34     Nicholas       Ross          73            100
17      Bridget    Johnson          92            100
26  Christopher      Rocha          97            100
3       Jeffrey     Zuniga          77             99
25      Matthew     Foster          88             98
5         Erica      Lynch          74             96
46        Craig    Ferrell          94             96
35       Andrea   Robinson          81             95
0      Danielle       Wood         100             95
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
16      Jeffrey      Perez          74             89
31      Jessica      Baker          81             89
42       Jeremy     Conner          98             85
14        Debra    Cameron          65             84
32       Amanda   Richards          77             84
4          Jill       Wong          75             83
20        Linda      Clark          95             83
18         Lisa    Stewart          98             83
21        Helen       Hahn          72             82
37    Christine      Hicks          65             80
47       Joshua       Rice          67             80
41      Brandon     Burton          82             80
1         Angel      Clark          67             78
10      Jeffery       Mayo          97             78
33       Teresa      Hurst          69             77
15          Amy    Parsons          73             77
43        Keith  Henderson          76             77
23         Eric    Edwards          86             77
29    Cassandra     Wright          70             75
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
36        Maria     Bright          66             74
39      Barbara   Williams          66             74
48      Cynthia     Maddox          84             73
45        Jesse      James          89             73
22      Matthew     Walter          94             73
6      Patricia    Jackson          68             72
19         Adam      Adams          61             70
27        Colin      Ellis          77             70
30      Lindsay    Hoffman          87             70
13        James      Cohen          61             66
11      William     Bowman          87             65
44  Christopher      Brown          62             64
7   Christopher     Daniel          66             64
24        Susan       Rios          74             64
38     Michelle      Davis          84             63
40        Janet  Rodriguez          82             62
8        Robert     Martin          94             62

### 🧪 3. Filtering with Conditions

In [14]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
8        Robert    Martin          94             62
10      Jeffery      Mayo          97             78
17      Bridget   Johnson          92            100
18         Lisa   Stewart          98             83
20        Linda     Clark          95             83
22      Matthew    Walter          94             73
26  Christopher     Rocha          97            100
42       Jeremy    Conner          98             85
46        Craig   Ferrell          94             96

In [15]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["science_score"] < 70)]

     first_name  last_name  math_score  science_score
1         Angel      Clark          67             78
2        Joshua      Adams          61            100
6      Patricia    Jackson          68             72
7   Christopher     Daniel          66             64
8        Robert     Martin          94             62
9       Anthony       Gray          65             74
11      William     Bowman          87             65
12      Anthony    Hawkins          62             74
13        James      Cohen          61             66
14        Debra    Cameron          65             84
19         Adam      Adams          61             70
24        Susan       Rios          74             64
28      Melanie      Baker          60             94
33       Teresa      Hurst          69             77
36        Maria     Bright          66             74
37    Christine      Hicks          65             80
38     Michelle      Davis          84             63
39      Barbara   Williams          66             74
40        Janet  Rodriguez          82             62
44  Christopher      Brown          62             64
47       Joshua       Rice          67             80
49      Michael   Valencia          65             91

### 🔗 4. Combining Filters

In [16]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
17      Bridget   Johnson          92            100
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
46        Craig   Ferrell          94             96

### 🧾 5. Using `.query()` for Readability

In [17]:
# Same query using .query()
df.query("math_score >= 87 and science_score >= 87")

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
17      Bridget   Johnson          92            100
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
46        Craig   Ferrell          94             96

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [18]:
# Sorting by first name alphabetically
df.sort_values(by = "first_name")

     first_name  last_name  math_score  science_score
19         Adam      Adams          61             70
32       Amanda   Richards          77             84
15          Amy    Parsons          73             77
35       Andrea   Robinson          81             95
1         Angel      Clark          67             78
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
39      Barbara   Williams          66             74
41      Brandon     Burton          82             80
17      Bridget    Johnson          92            100
29    Cassandra     Wright          70             75
37    Christine      Hicks          65             80
44  Christopher      Brown          62             64
26  Christopher      Rocha          97            100
7   Christopher     Daniel          66             64
27        Colin      Ellis          77             70
46        Craig    Ferrell          94             96
48      Cynthia     Maddox          84             73
0      Danielle       Wood         100             95
14        Debra    Cameron          65             84
23         Eric    Edwards          86             77
5         Erica      Lynch          74             96
21        Helen       Hahn          72             82
13        James      Cohen          61             66
40        Janet  Rodriguez          82             62
10      Jeffery       Mayo          97             78
16      Jeffrey      Perez          74             89
3       Jeffrey     Zuniga          77             99
42       Jeremy     Conner          98             85
45        Jesse      James          89             73
31      Jessica      Baker          81             89
4          Jill       Wong          75             83
2        Joshua      Adams          61            100
47       Joshua       Rice          67             80
43        Keith  Henderson          76             77
20        Linda      Clark          95             83
30      Lindsay    Hoffman          87             70
18         Lisa    Stewart          98             83
36        Maria     Bright          66             74
25      Matthew     Foster          88             98
22      Matthew     Walter          94             73
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
38     Michelle      Davis          84             63
34     Nicholas       Ross          73            100
6      Patricia    Jackson          68             72
8        Robert     Martin          94             62
24        Susan       Rios          74             64
33       Teresa      Hurst          69             77
11      William     Bowman          87             65

In [24]:
# Finding students with the same math and science score 
df[df["math_score"] == df["science_score"]]

Empty DataFrame
Columns: [first_name, last_name, math_score, science_score]
Index: []

In [34]:
# Finding students that scored over 95 in either subject
df.query("math_score > 95" or "science_score > 95")

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
10      Jeffery      Mayo          97             78
18         Lisa   Stewart          98             83
26  Christopher     Rocha          97            100
42       Jeremy    Conner          98             85

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [39]:
# Mini-challenge

# 1. Sorting out students by the most recent signup date 
df.sort_values(by = "signup_date")

,first_name,last_name,math_score,science_score,signup_date,survey_completed,major,grade_level
13,James,Cohen,61,66,2025-02-25,NaN,Business,Junior
19,Adam,Adams,61,70,2025-02-26,NaN,Business,Freshman
6,Patricia,Jackson,68,72,2025-02-27,NaN,Psychology,Sophomore
38,Michelle,Davis,84,63,2025-02-28,NaN,Chemistry,Senior
44,Christopher,Brown,62,64,2025-03-01,NaN,History,Freshman
24,Susan,Rios,74,64,2025-03-01,NaN,English,Sophomore
7,Christopher,Daniel,66,64,2025-03-02,Yes,Business,Freshman
36,Maria,Bright,66,74,2025-03-03,Yes,History,Junior
29,Cassandra,Wright,70,75,2025-03-04,Yes,Business,Sophomore
39,Barbara,Williams,66,74,2025-03-05,Yes,Business,Freshman
9,Anthony,Gray,65,74,2025-03-05,NaN,Math,Sophomore
12,Anthony,Hawkins,62,74,2025-03-06,Yes,History,Freshman
27,Colin,Ellis,77,70,2025-03-07,Yes,History,Junior
21,Helen,Hahn,72,82,2025-03-08,Yes,Nursing,Junior
43,Keith,Henderson,76,77,2025-03-09,Yes,Math,Junior
4,Jill,Wong,75,83,2025-03-09,Yes,CS,Senior
23,Eric,Edwards,86,77,2025-03-10,Yes,Math,Junior
11,William,Bowman,87,65,2025-03-11,Yes,Physics,Senior
15,Amy,Parsons,73,77,2025-03-12,Yes,English,Sophomore
33,Teresa,Hurst,69,77,2025-03-13,NaN,English,Sophomore
47,Joshua,Rice,67,80,2025-03-14,Yes,Biology,Sophomore
1,Angel,Clark,67,78,2025-03-14,Yes,Math,Sophomore
37,Christine,Hicks,65,80,2025-03-15,Yes,Psychology,Sophomore
32,Amanda,Richards,77,84,2025-03-16,Yes,Math,Junior
22,Matthew,Walter,94,73,2025-03-17,Yes,Engineering,Senior
40,Janet,Rodriguez,82,62,2025-03-18,Yes,English,Senior
8,Robert,Martin,94,62,2025-03-18,Yes,Engineering,Senior
30,Lindsay,Hoffman,87,70,2025-03-19,Yes,Psychology,Senior
45,Jesse,James,89,73,2025-03-20,Yes,Business,Senior
20,Linda,Clark,95,83,2025-03-20,Yes,Psychology,Senior
31,Jessica,Baker,81,89,2025-03-21,Yes,CS,Junior
41,Brandon,Burton,82,80,2025-03-22,Yes,CS,Junior
14,Debra,Cameron,65,84,2025-03-22,Yes,Nursing,Senior
28,Melanie,Baker,60,94,2025-03-23,Yes,Biology,Freshman
48,Cynthia,Maddox,84,73,2025-03-24,Yes,Nursing,Junior
16,Jeffrey,Perez,74,89,2025-03-24,Yes,CS,Junior
3,Jeffrey,Zuniga,77,99,2025-03-25,Yes,History,Junior
18,Lisa,Stewart,98,83,2025-03-26,Yes,Chemistry,Junior
10,Jeffery,Mayo,97,78,2025-03-27,Yes,CS,Junior
35,Andrea,Robinson,81,95,2025-03-27,Yes,Nursing,Senior
0,Danielle,Wood,100,95,2025-03-28,Yes,CS,Senior
49,Michael,Valencia,65,91,2025-03-28,Yes,CS,Senior
25,Matthew,Foster,88,98,2025-03-29,Yes,Physics,Senior
42,Jeremy,Conner,98,85,2025-03-30,Yes,Physics,Senior
5,Erica,Lynch,74,96,2025-03-30,Yes,English,Junior
46,Craig,Ferrell,94,96,2025-03-31,Yes,Engineering,Junior
2,Joshua,Adams,61,100,2025-03-31,Yes,Biology,Freshman
17,Bridget,Johnson,92,100,2025-04-01,Yes,Biology,Senior
26,Christopher,Rocha,97,100,2025-04-02,Yes,CS,Senior
34,Nicholas,Ross,73,100,2025-04-03,Yes,Engineering,Freshman

In [52]:
# Filtering out anyone who has not completed the survey
df[df["survey_completed"] != "Yes"]

,first_name,last_name,math_score,science_score,signup_date,survey_completed,major,grade_level
6,Patricia,Jackson,68,72,2025-02-27,NaN,Psychology,Sophomore
9,Anthony,Gray,65,74,2025-03-05,NaN,Math,Sophomore
13,James,Cohen,61,66,2025-02-25,NaN,Business,Junior
19,Adam,Adams,61,70,2025-02-26,NaN,Business,Freshman
24,Susan,Rios,74,64,2025-03-01,NaN,English,Sophomore
33,Teresa,Hurst,69,77,2025-03-13,NaN,English,Sophomore
38,Michelle,Davis,84,63,2025-02-28,NaN,Chemistry,Senior
44,Christopher,Brown,62,64,2025-03-01,NaN,History,Freshman

In [49]:
# Using Query to filter out the CS majors at any level
df.query("major == 'CS'")

,first_name,last_name,math_score,science_score,signup_date,survey_completed,major,grade_level
0,Danielle,Wood,100,95,2025-03-28,Yes,CS,Senior
4,Jill,Wong,75,83,2025-03-09,Yes,CS,Senior
10,Jeffery,Mayo,97,78,2025-03-27,Yes,CS,Junior
16,Jeffrey,Perez,74,89,2025-03-24,Yes,CS,Junior
26,Christopher,Rocha,97,100,2025-04-02,Yes,CS,Senior
31,Jessica,Baker,81,89,2025-03-21,Yes,CS,Junior
41,Brandon,Burton,82,80,2025-03-22,Yes,CS,Junior
49,Michael,Valencia,65,91,2025-03-28,Yes,CS,Senior

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |