
# 🧼 Data Cleaning Lab: Survey Edition

Welcome to the data cleaning battlefield! This notebook contains a messy `survey_dirty.csv` file full of inconsistencies, missing values, and formatting nightmares. Your task is to clean it up using pandas and your data wrangling skills.

---

📁 **File to use**: `survey_dirty.csv`  
📊 **Goal**: Practice common data cleaning tasks on a realistic (but slightly cursed) dataset.


## ✅ Cleaning Tasks

Complete the following tasks step-by-step. Use new cells for each task and document your process.

### 1. Load and inspect the data
- Load the CSV file into a DataFrame
- Display the first few rows and basic info (`df.info()`)

### 2. Clean up string fields
- Strip whitespace from `name`, `email`, and other string columns
- Identify blank strings and convert them to NaN if needed

### 3. Handle missing values
- Identify columns with missing data
- Decide how to handle them: drop, fill, or flag (justify your choices)

### 4. Standardize categorical data
- Convert `gender` values to consistent categories (`Male`, `Female`, `Other`)
- Normalize `exercise_freq` to a standard set of categories

### 5. Fix data types
- Convert `age`, `height_cm`, `weight_kg`, and `satisfaction` to numeric
- Extract numbers from strings (e.g., "175cm" → 175)
- Convert `submitted_at` to datetime

### 6. Validate and clean emails
- Use regex or string methods to filter out invalid email addresses

### 7. Convert consent to Boolean
- Standardize `consent_given` to True/False values

### 8. Check for duplicates
- Identify any duplicated rows or IDs
- Drop or resolve as needed

### 9. Save your cleaned data
- Save the cleaned DataFrame to a new file called `survey_clean.csv`

In [2]:

import pandas as pd

# Load the messy data
df = pd.read_csv("survey_dirty.csv")
df.head()

,respondent_id,name,email,gender,exercise_freq,age,height_cm,weight_kg,satisfaction,submitted_at,consent_given
0,1001,Alice Johnson,alice.johnson@example.com,F,daily,22,165cm,58kg,5,2025-03-01 09:15:00,Yes
1,1002,Bob Smith,bob.smith@example,M,3x/week,27 years,180 cm,82 kg,4,03/02/2025 14:30,Y
2,1003,Carla Gomez,carla.gomez@example.com,female,Weekly,,172cm,68kg,3,2025/03/03 08:00,true
3,1004,David Lee,david.lee@sample.org,Male,never,31,175,,2,March 4 2025 6:45 PM,No
4,1005,Emily Davis,emily.davis@example.com,Female,2 times/week,29,169 cm,61kg,4,2025-03-05T12:00:00,TRUE

In [ ]:
# 1.- Displaying the info of the data frame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   respondent_id  16 non-null     int64
 1   name           16 non-null     str
 2   email          15 non-null     str
 3   gender         16 non-null     str
 4   exercise_freq  15 non-null     str
 5   age            16 non-null     str
 6   height_cm      15 non-null     str
 7   weight_kg      16 non-null     str
 8   satisfaction   16 non-null     str
 9   submitted_at   16 non-null     str
 10  consent_given  15 non-null     str
dtypes: int64(1), str(10)
memory usage: 1.5 KB

In [4]:
# 2.- Cleaning up string fields by removing extra spaces and turning empty strings
# into missing values 

import pandas as pd

# Clean whitespace in string columns
string_cols = ["name", "email", "gender", "exercise_freq", "consent_given"]

for col in string_cols:
    df[col] = df[col].astype("string").str.strip()

# Converting blank strings to NaN
df[string_cols] = df[string_cols].replace("", pd.NA)
df.head()

,respondent_id,name,email,gender,exercise_freq,age,height_cm,weight_kg,satisfaction,submitted_at,consent_given
0,1001,Alice Johnson,alice.johnson@example.com,F,daily,22,165cm,58kg,5,2025-03-01 09:15:00,Yes
1,1002,Bob Smith,bob.smith@example,M,3x/week,27 years,180 cm,82 kg,4,03/02/2025 14:30,Y
2,1003,Carla Gomez,carla.gomez@example.com,female,Weekly,,172cm,68kg,3,2025/03/03 08:00,true
3,1004,David Lee,david.lee@sample.org,Male,never,31,175,,2,March 4 2025 6:45 PM,No
4,1005,Emily Davis,emily.davis@example.com,Female,2 times/week,29,169 cm,61kg,4,2025-03-05T12:00:00,TRUE

In [ ]:
# 3.- Handling missing values

# Checking how many values are missing
df.isna().sum()

respondent_id    0
name             0
email            1
gender           0
exercise_freq    1
age              0
height_cm        1
weight_kg        0
satisfaction     0
submitted_at     0
consent_given    1
dtype: int64

In [11]:
# Fill missing categorical values with by dropping the items
# Justification: I dropped rows with missing required survey fields instead of filling them
# because I did not want to invent a category values that were not actually provided
df = df.dropna(subset=["name", "gender", "exercise_freq", "consent_given"])
df.head()

,respondent_id,name,email,gender,exercise_freq,age,height_cm,weight_kg,satisfaction,submitted_at,consent_given
0,1001,Alice Johnson,alice.johnson@example.com,F,daily,22,165cm,58kg,5,2025-03-01 09:15:00,Yes
1,1002,Bob Smith,bob.smith@example,M,3x/week,27 years,180 cm,82 kg,4,03/02/2025 14:30,Y
2,1003,Carla Gomez,carla.gomez@example.com,female,Weekly,,172cm,68kg,3,2025/03/03 08:00,true
3,1004,David Lee,david.lee@sample.org,Male,never,31,175,,2,March 4 2025 6:45 PM,No
4,1005,Emily Davis,emily.davis@example.com,Female,2 times/week,29,169 cm,61kg,4,2025-03-05T12:00:00,TRUE

In [ ]:
# 4.- Standardizing categorical data

import pandas as pd

df = pd.read_csv("survey_dirty.csv")

string_cols = ["name", "email", "gender", "exercise_freq", "consent_given"]
for col in string_cols:
    df[col] = df[col].astype("string").str.strip()

df[string_cols] = df[string_cols].replace("", pd.NA)
df = df.dropna(subset=["name", "gender", "exercise_freq", "consent_given"])

# Converting gender values to consistent categories
gender_map = {
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female",
    "woman": "Female",
    "nonbinary": "Other",
    "other": "Other"
}

df["gender"] = df["gender"].str.lower().map(gender_map)

# Normalizing exercise frequency into standard categories
exercise_map = {
    "daily": "Daily",
    "every day": "Daily",
    "weekly": "Weekly",
    "once a week": "Weekly",
    "3x/week": "Weekly",
    "3x weekly": "Weekly",
    "2 times/week": "Weekly",
    "1-2 times": "Weekly",
    "sometimes": "Rarely",
    "rarely": "Rarely",
    "never": "Never"
}

df["exercise_freq"] = df["exercise_freq"].str.lower().map(exercise_map)

df[["gender", "exercise_freq"]].drop_duplicates().sort_values(["gender", "exercise_freq"])

    gender exercise_freq
0   Female         Daily
10  Female         Never
2   Female        Weekly
5     Male         Daily
3     Male         Never
7     Male        Rarely
1     Male        Weekly
11   Other         Daily
6    Other        Rarely

In [ ]:
# 5.- Fixing data types

age_words = {"thirty": "30"}
df["age"] = df["age"].astype("string").str.strip().replace(age_words)

df["age"] = pd.to_numeric(df["age"].str.extract(r"(\d+)", expand=False), errors="coerce")
df["height_cm"] = pd.to_numeric(df["height_cm"].astype("string").str.extract(r"(\d+)", expand=False), errors="coerce")
df["weight_kg"] = pd.to_numeric(df["weight_kg"].astype("string").str.extract(r"(\d+)", expand=False), errors="coerce")
df["satisfaction"] = pd.to_numeric(df["satisfaction"], errors="coerce")
df["submitted_at"] = pd.to_datetime(df["submitted_at"], errors="coerce")

df[["age", "height_cm", "weight_kg", "satisfaction", "submitted_at"]].head()

    age  height_cm  weight_kg  satisfaction        submitted_at
0    22        165         58           5.0 2025-03-01 09:15:00
1    27        180         82           4.0                 NaT
2  <NA>        172         68           3.0                 NaT
3    31        175       <NA>           2.0                 NaT
4    29        169         61           4.0                 NaT

In [4]:
# 6.- Validating and cleaning emails


email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

df["email_valid"] = df["email"].str.match(email_pattern, na=False)

print("Invalid emails:")
print(df.loc[~df["email_valid"], ["name", "email"]])

df = df[df["email_valid"]].copy()

df[["name", "email", "email_valid"]].head()

Invalid emails:
           name                    email
1     Bob Smith        bob.smith@example
5   Frank Moore                     <NA>
10  Karen Patel  karen.patel at mail.com

            name                      email  email_valid
0  Alice Johnson  alice.johnson@example.com         True
2    Carla Gomez    carla.gomez@example.com         True
3      David Lee       david.lee@sample.org         True
4    Emily Davis    emily.davis@example.com         True
6      Grace Kim      grace.kim@example.com         True

In [5]:
#7.- Converting consent_given to Boolean


consent_map = {
    "yes": True,
    "y": True,
    "true": True,
    "no": False,
    "n": False,
    "false": False
}

df["consent_given"] = df["consent_given"].str.lower().map(consent_map)

df[["name", "consent_given"]].head()

            name consent_given
0  Alice Johnson          True
2    Carla Gomez          True
3      David Lee         False
4    Emily Davis          True
6      Grace Kim           NaN

In [6]:
# 8.- Checking for duplicates

import pandas as pd

# Reload and re-clean the data so this cell works by itself
df = pd.read_csv("survey_dirty.csv")

string_cols = ["name", "email", "gender", "exercise_freq", "consent_given"]
for col in string_cols:
    df[col] = df[col].astype("string").str.strip()

df[string_cols] = df[string_cols].replace("", pd.NA)
df = df.dropna(subset=["name", "gender", "exercise_freq", "consent_given"])

# Find duplicate rows and duplicate respondent IDs
print("Duplicate rows:")
print(df[df.duplicated()])

print("\nDuplicate respondent_id values:")
print(df[df.duplicated(subset=["respondent_id"], keep=False)])

# Drop full duplicate rows
df = df.drop_duplicates()

df.head()

Duplicate rows:
    respondent_id         name                    email gender exercise_freq  \
15           1015  Olivia Hall  olivia.hall@example.com  woman   Once a week

   age height_cm weight_kg satisfaction         submitted_at consent_given
15  26     167cm      60kg            4  2025-03-15 08:45:00           YES

Duplicate respondent_id values:
    respondent_id         name                    email gender exercise_freq  \
14           1015  Olivia Hall  olivia.hall@example.com  woman   Once a week
15           1015  Olivia Hall  olivia.hall@example.com  woman   Once a week

   age height_cm weight_kg satisfaction         submitted_at consent_given
14  26     167cm      60kg            4  2025-03-15 08:45:00           YES
15  26     167cm      60kg            4  2025-03-15 08:45:00           YES

,respondent_id,name,email,gender,exercise_freq,age,height_cm,weight_kg,satisfaction,submitted_at,consent_given
0,1001,Alice Johnson,alice.johnson@example.com,F,daily,22,165cm,58kg,5,2025-03-01 09:15:00,Yes
1,1002,Bob Smith,bob.smith@example,M,3x/week,27 years,180 cm,82 kg,4,03/02/2025 14:30,Y
2,1003,Carla Gomez,carla.gomez@example.com,female,Weekly,,172cm,68kg,3,2025/03/03 08:00,true
3,1004,David Lee,david.lee@sample.org,Male,never,31,175,,2,March 4 2025 6:45 PM,No
4,1005,Emily Davis,emily.davis@example.com,Female,2 times/week,29,169 cm,61kg,4,2025-03-05T12:00:00,TRUE

In [7]:
# 9.- Saving the cleaned data

import pandas as pd

# Reload and re-clean the data so this cell works by itself
df = pd.read_csv("survey_dirty.csv")

string_cols = ["name", "email", "gender", "exercise_freq", "consent_given"]
for col in string_cols:
    df[col] = df[col].astype("string").str.strip()

df[string_cols] = df[string_cols].replace("", pd.NA)
df = df.dropna(subset=["name", "gender", "exercise_freq", "consent_given"])

# Standardize categorical columns
gender_map = {
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female",
    "woman": "Female",
    "nonbinary": "Other",
    "other": "Other"
}
df["gender"] = df["gender"].str.lower().map(gender_map)

exercise_map = {
    "daily": "Daily",
    "every day": "Daily",
    "weekly": "Weekly",
    "once a week": "Weekly",
    "3x/week": "Weekly",
    "3x weekly": "Weekly",
    "2 times/week": "Weekly",
    "1-2 times": "Weekly",
    "sometimes": "Rarely",
    "rarely": "Rarely",
    "never": "Never"
}
df["exercise_freq"] = df["exercise_freq"].str.lower().map(exercise_map)

consent_map = {
    "yes": True,
    "y": True,
    "true": True,
    "no": False,
    "n": False,
    "false": False
}
df["consent_given"] = df["consent_given"].str.lower().map(consent_map)

age_words = {"thirty": "30"}
df["age"] = df["age"].astype("string").str.strip().replace(age_words)

df["age"] = pd.to_numeric(df["age"].str.extract(r"(\d+)", expand=False), errors="coerce")
df["height_cm"] = pd.to_numeric(df["height_cm"].astype("string").str.extract(r"(\d+)", expand=False), errors="coerce")
df["weight_kg"] = pd.to_numeric(df["weight_kg"].astype("string").str.extract(r"(\d+)", expand=False), errors="coerce")
df["satisfaction"] = pd.to_numeric(df["satisfaction"], errors="coerce")
df["submitted_at"] = pd.to_datetime(df["submitted_at"], errors="coerce")

email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"
df["email_valid"] = df["email"].str.match(email_pattern, na=False)
df = df[df["email_valid"]].copy()

# Remove duplicate rows before saving
df = df.drop_duplicates()

# Save cleaned dataset
df.to_csv("survey_cleaned.csv", index=False)

print("Cleaned file saved as survey_cleaned.csv")
df.head()

Cleaned file saved as survey_cleaned.csv

,respondent_id,name,email,gender,exercise_freq,age,height_cm,weight_kg,satisfaction,submitted_at,consent_given,email_valid
0,1001,Alice Johnson,alice.johnson@example.com,Female,Daily,22,165,58,5.0,2025-03-01 09:15:00,True,True
2,1003,Carla Gomez,carla.gomez@example.com,Female,Weekly,<NA>,172,68,3.0,NaT,True,True
3,1004,David Lee,david.lee@sample.org,Male,Never,31,175,<NA>,2.0,NaT,False,True
4,1005,Emily Davis,emily.davis@example.com,Female,Weekly,29,169,61,4.0,NaT,True,True
6,1007,Grace Kim,grace.kim@example.com,Other,Rarely,24,160,55,NaN,2025-03-07 07:20:00,NaN,True