# 🧱 Column Operations: Creating, Renaming, and Dropping Columns

## 🔹 LEARNING GOALS:
- Create new columns using calculations or functions
- Rename one or multiple columns
- Drop unwanted columns safely
- Apply functions across columns using `.apply()` and lambdas

### 🏗️ 1. Setup and Sample Data

In [1]:
import pandas as pd

data = {
    "first_name": ["Alice", "Bob", "Charlie", "David"],
    "last_name": ["Smith", "Jones", "Brown", "Wilson"],
    "math_score": [85, 90, 78, 92],
    "science_score": [88, 85, 82, 95]
}

df = pd.DataFrame(data)
df

  first_name last_name  math_score  science_score
0      Alice     Smith          85             88
1        Bob     Jones          90             85
2    Charlie     Brown          78             82
3      David    Wilson          92             95

### ➕ 2. Creating New Columns

In [3]:
# Simple column arithmetic
df["average_score"] = (df["math_score"] + df["science_score"]) / 2
df

  first_name last_name  math_score  science_score  average_score
0      Alice     Smith          85             88           86.5
1        Bob     Jones          90             85           87.5
2    Charlie     Brown          78             82           80.0
3      David    Wilson          92             95           93.5

In [4]:
# Create full name column
df["full_name"] = df["first_name"] + " " + df["last_name"]
df

,first_name,last_name,math_score,science_score,average_score,full_name
0,Alice,Smith,85,88,86.5,Alice Smith
1,Bob,Jones,90,85,87.5,Bob Jones
2,Charlie,Brown,78,82,80.0,Charlie Brown
3,David,Wilson,92,95,93.5,David Wilson

### ✍️ 3. Renaming Columns

In [5]:
# Rename a single column
df.rename(columns={"math_score": "Math", "science_score": "Science"}, inplace=True)
df

  first_name last_name  Math  Science  average_score      full_name
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

In [6]:
# Rename all columns to uppercase
df.columns = [col.upper() for col in df.columns]
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE      FULL_NAME
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

### ❌ 4. Dropping Columns

In [7]:
# Drop by name
df.drop(columns=["FULL_NAME"], inplace=True)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE
0      Alice     Smith    85       88           86.5
1        Bob     Jones    90       85           87.5
2    Charlie     Brown    78       82           80.0
3      David    Wilson    92       95           93.5

### 🔁 5. Applying Functions Across Columns

In [8]:
# Categorize based on average score
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

df["GRADE"] = df["AVERAGE_SCORE"].apply(grade)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE GRADE
0      Alice     Smith    85       88           86.5     B
1        Bob     Jones    90       85           87.5     B
2    Charlie     Brown    78       82           80.0     B
3      David    Wilson    92       95           93.5     A

### 🧪 Try It Yourself

- Add a new column called `"NAME_LENGTH"` that contains the length of each `FIRST_NAME`
- Create a column `"MATH_PLUS_5"` which is the math score + 5 points bonus

In [7]:
# New column that contains the length of each student's first name

import pandas as pd

data = {
    "first_name": ["Alice", "Bob", "Charlie", "David"],
    "last_name": ["Smith", "Jones", "Brown", "Wilson"],
    "math_score": [85, 90, 78, 92],
    "science_score": [88, 85, 82, 95]
    }





df = pd.DataFrame(data)
df.columns = [col.upper() for col in df.columns]
df["NAME_LENGTH"] = df["FIRST_NAME"].apply(len)
df

  FIRST_NAME LAST_NAME  MATH_SCORE  SCIENCE_SCORE  NAME_LENGTH
0      Alice     Smith          85             88            5
1        Bob     Jones          90             85            3
2    Charlie     Brown          78             82            7
3      David    Wilson          92             95            5

In [9]:
# Column called MATH_PLUS which is math score plus 5 points extra credit

df["MATH_PLUS"] = df["MATH_SCORE"] + 5
df

  FIRST_NAME LAST_NAME  MATH_SCORE  SCIENCE_SCORE  NAME_LENGTH  MATH_PLUS
0      Alice     Smith          85             88            5         90
1        Bob     Jones          90             85            3         95
2    Charlie     Brown          78             82            7         83
3      David    Wilson          92             95            5         97

### 🧠 Mini-Challenge

> Load `"data/students.csv"` and:
- Create a `"total_score"` column by summing up all numeric test columns
- Rename any columns that contain spaces (e.g., `"Test 1"`) to use underscores
- Drop any column that contains only `NaN` values

In [10]:
# Loading data from data students.csv
import pandas as pd

df = pd.read_csv("/Users/josemarioomrqz/4543-5993-Spatial-Data/Assignments/01-Python_Foundations/05-Working_with_Data_Adv/data/survey.csv")
df.head()

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

In [13]:
# Renaming columns that contain spaces to use underscores instead

df.rename(columns=lambda x: x.strip().replace(" ", "_"), inplace=True)
df.head()

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

In [17]:
# Dropping columns that contain NaN values 

df.dropna(axis=1, how="all", inplace=True)
df.head()

  student_id
0     S10000
1     S10001
2     S10002
3     S10003
4     S10004

### 📝 Summary

| Action             | Method                                |
|--------------------|----------------------------------------|
| Create column       | `df["new"] = ...`                     |
| Rename column(s)    | `df.rename(columns={...})`            |
| Rename all columns  | `df.columns = [...]`                 |
| Drop column(s)      | `df.drop(columns=[...])`              |
| Apply function      | `df["col"].apply(func)`               |